# Generated by Django 5.1.1 on 2024-09-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_roundinfoerrorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='awayScore_normaltime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='awayScore_period1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='awayScore_period2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='homeScore_normaltime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='homeScore_period1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='homeScore_period2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
