# Generated by Django 5.1.1 on 2024-09-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_matchinfo_awayscore_normaltime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDataError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('round_num', models.IntegerField()),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
